### ISSUE TITLE
The third step is to become a zombie,experiment.xml file content is empty。

### ISSUE THREAD

**Issue by akkbook** [HPCToolkit/hpctoolkit#147]
The third step is to become a zombie,experiment.xml file content is empty。

OS: redhat-7.2
gcc: version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) .
mpi: mpich gnu 3.3.1
soft: hpctoolkit-release-2017.10.tar.gz hpctoolkit-externals-release-2017.06.tar.gz
Would you give me some advice?

**Comment by mwkrentel** [comment]
The 2017 version is VERY old and hpctoolkit-externals is no longer
supported.  Please try again with a current version and use spack to
build the dependencies.

http://hpctoolkit.org/software-instructions.html

As for why you have an empty database file, I don't know.  Except to
say that it's a common mistake to run the 'hello world' program that
takes 0.001 seconds and end up with zero samples.  Especially here
since you're sampling at a rate of only 2 per second (500,000
microseconds).

**Comment by akkbook** [comment]
Thank you for your advice.
