### ISSUE TITLE
dlstress test deadlocks hpcrun

### ISSUE THREAD

**Issue by mwkrentel** [HPCToolkit/hpctoolkit#200]
Back in 2009, I wrote a dlstress unit test as part of fixing a LOR
(lock order reversal) problem in hpcrun.  The test runs two threads
and hammers the system with a loop of dlopen(), dlclose() and
dl_iterate_phdr() from interrupts.  This is designed to expose if
hpcrun is vulnerable to deadlock from the dlopen and fnbounds locks.

I recently tried the test and the deadlock is back.

I'll attach a tar file with the source code and Makefile.  It builds
easily with 'make'.

The normal way of running is as follows.  This runs two threads with
both readers (dl_iterate_phdr from interrupts) and writers (dlopen and
dlclose from the app).

```
hpcrun -e REALTIME@500 ./dlstress <num-seconds> x x
```

For me on gpu.cs, `dlstress 30 x x` with REALTIME at 500 and hpcrun
master (after the big merge) deadlocks maybe 20% of the time.  Very
rarely, if at all before the merge.

Honestly, the program and LOR fixes are so old that I barely
understand what they do. :-(  But I remember that I fixed the LOR
problems where dlstress would never deadlock.

----------

1. For me, REALTIME@500 deadlocks maybe 20% of the time.  Actually,
sometimes it seems to deadlock nearly every run, and sometimes it
takes 20 runs to get a deadlock.

2. CPUTIME@500 deadlocks very rarely.  I don't understand this.  It
must be that REALTIME is better at hitting a window of vulnerability.
But I don't think it's related to select() or poll(), the normal ways
that REALTIME is more stressful than CPUTIME.

3. I can reliably make master deadlock after the gpu merge.  I just
have to run it enough times.  I think it does deadlock before the
merge, but maybe only 1-2% of the time.

4. Back in 2009, we didn't have REALTIME, so I would have used
PAPI_TOT_CYCLES at a fast rate.  Cycles is closer to CPUTIME because
they both only advance the counter in user mode (not kernel).  So,
maybe REALTIME would have exposed a problem back in 2009.

5. ~~hpcrun with perf CYCLES@200 deadlocks dlstress nearly 100% of the
time, always early, with different stack trace.~~

Never mind about (5).  CYCLES@200 was a mistake.  I meant to use
CYCLES@f200 which is very different.

6. Don't worry that 99% of interrupts result in dlopen blocks in the
summary.  This is normal.

Anyway, we need to understand the deadlock to fix the code paths.
Maybe we need to drop more samples in certain cases.

----------

Sample stack traces from REALTIME.

Thread 1:

```
#0  0x00007f691232c54d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f6912327eb6 in _L_lock_941 () from /lib64/libpthread.so.0
#2  0x00007f6912327daf in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00007f691208d0ef in dl_iterate_phdr () from /lib64/libc.so.6
#4  0x00007f69119211b7 in _ULx86_64_dwarf_find_proc_info (as=0x7f6911b292a0 <local_addr_space>, 
    ip=ip@entry=140089253596896, pi=pi@entry=0x7ffc5e38cd18, need_unwind_info=need_unwind_info@entry=1, 
    arg=0x7ffc5e38cbc0) at dwarf/Gfind_proc_info-lsb.c:708
#5  0x00007f691191e747 in fetch_proc_info (c=c@entry=0x7ffc5e38cbc0, ip=140089253596896) at dwarf/Gparser.c:454
#6  0x00007f691192071c in _ULx86_64_dwarf_reg_states_iterate (c=0x7ffc5e38cbc0, 
    cb=0x7f69129aff70 <dwarf_reg_states_callback>, token=0x7ffc5e38c7f0) at dwarf/Gparser.c:1034
#7  0x00007f69129b030a in libunw_build_intervals ()
   from /home/krentel/dlstress/hpctoolkit/install/lib/hpctoolkit/libhpcrun.so
#8  0x00007f69129b5a7e in build_intervals () from /home/krentel/dlstress/hpctoolkit/install/lib/hpctoolkit/libhpcrun.so
#9  0x00007f69129b10d9 in uw_recipe_map_lookup ()
   from /home/krentel/dlstress/hpctoolkit/install/lib/hpctoolkit/libhpcrun.so
#10 0x00007f69129b009a in libunw_finalize_cursor ()
   from /home/krentel/dlstress/hpctoolkit/install/lib/hpctoolkit/libhpcrun.so
#11 0x00007f69129b5997 in hpcrun_unw_init_cursor ()
   from /home/krentel/dlstress/hpctoolkit/install/lib/hpctoolkit/libhpcrun.so
#12 0x00007f69129af087 in hpcrun_generate_backtrace_no_trampoline ()
   from /home/krentel/dlstress/hpctoolkit/install/lib/hpctoolkit/libhpcrun.so
#13 0x00007f69129af436 in hpcrun_generate_backtrace ()
   from /home/krentel/dlstress/hpctoolkit/install/lib/hpctoolkit/libhpcrun.so
#14 0x00007f691298397a in hpcrun_backtrace2cct ()
   from /home/krentel/dlstress/hpctoolkit/install/lib/hpctoolkit/libhpcrun.so
#15 0x00007f6912986fb7 in hpcrun_sample_callpath ()
   from /home/krentel/dlstress/hpctoolkit/install/lib/hpctoolkit/libhpcrun.so
#16 0x00007f691298aa42 in itimer_signal_handler ()
   from /home/krentel/dlstress/hpctoolkit/install/lib/hpctoolkit/libhpcrun.so
#17 0x00007f69127444ad in monitor_signal_handler ()
   from /home/krentel/dlstress/hpctoolkit/install/lib/hpctoolkit/ext-libs/libmonitor.so
#18 <signal handler called>
#19 0x00007f6912328ee0 in pthread_mutex_unlock () from /lib64/libpthread.so.0
#20 0x00007f691253b12d in dlsym () from /lib64/libdl.so.2
#21 0x00000000004009d8 in do_cycles (la=la@entry=0x7ffc5e38e350, handle=handle@entry=0x1173010, num=num@entry=13)
    at dlstress.c:120
#22 0x0000000000400c82 in do_loop (la=la@entry=0x7ffc5e38e350) at dlstress.c:182
#23 0x0000000000401042 in main (argc=4, argv=0x7ffc5e38e528) at dlstress.c:318
```

Thread 2:

```
#0  0x00007f691232c54d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f6912327eb6 in _L_lock_941 () from /lib64/libpthread.so.0
#2  0x00007f6912327daf in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00007f6912c08aee in _dl_open () from /lib64/ld-linux-x86-64.so.2
#4  0x00007f691253afab in dlopen_doit () from /lib64/libdl.so.2
#5  0x00007f6912c047a4 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#6  0x00007f691253b5ad in _dlerror_run () from /lib64/libdl.so.2
#7  0x00007f691253b041 in dlopen@@GLIBC_2.2.5 () from /lib64/libdl.so.2
#8  0x00007f691298db3d in lm_contains_fn () from /home/krentel/dlstress/hpctoolkit/install/lib/hpctoolkit/libhpcrun.so
#9  0x00007f691298de08 in module_ignore_map_ignore ()
   from /home/krentel/dlstress/hpctoolkit/install/lib/hpctoolkit/libhpcrun.so
#10 0x00007f6912985f00 in hpcrun_loadmap_map ()
   from /home/krentel/dlstress/hpctoolkit/install/lib/hpctoolkit/libhpcrun.so
#11 0x00007f69129a7f9b in fnbounds_ensure_mapped_dso ()
   from /home/krentel/dlstress/hpctoolkit/install/lib/hpctoolkit/libhpcrun.so
#12 0x00007f69129a89bb in dylib_map_open_dsos_callback ()
   from /home/krentel/dlstress/hpctoolkit/install/lib/hpctoolkit/libhpcrun.so
#13 0x00007f691208d1ac in dl_iterate_phdr () from /lib64/libc.so.6
#14 0x00007f69129a870f in dylib_map_open_dsos ()
   from /home/krentel/dlstress/hpctoolkit/install/lib/hpctoolkit/libhpcrun.so
#15 0x00007f69129a847b in hpcrun_dlopen () from /home/krentel/dlstress/hpctoolkit/install/lib/hpctoolkit/libhpcrun.so
#16 0x00007f6912982dba in monitor_dlopen () from /home/krentel/dlstress/hpctoolkit/install/lib/hpctoolkit/libhpcrun.so
#17 0x00007f69127428a4 in dlopen () from /home/krentel/dlstress/hpctoolkit/install/lib/hpctoolkit/ext-libs/libmonitor.so
#18 0x0000000000400c1e in do_loop (la=0x7ffc5e38e320) at dlstress.c:171
#19 0x0000000000400dbc in side_thread (data=<optimized out>) at dlstress.c:268
#20 0x00007f691274d26b in monitor_thread_fence2 ()
   from /home/krentel/dlstress/hpctoolkit/install/lib/hpctoolkit/ext-libs/libmonitor.so
#21 0x00007f6912325ea5 in start_thread () from /lib64/libpthread.so.0
#22 0x00007f691204e8cd in clone () from /lib64/libc.so.6
```

ping @jmellorcrummey @mxz297 
I need more eyes on this.

**Comment by mwkrentel** [comment]
Attach tar file.
[files.tar.gz](https://github.com/HPCToolkit/hpctoolkit/files/4169006/files.tar.gz)

**Comment by jmellorcrummey** [comment]
it is clear what the problem is here. one thread is deadlocking with itself. 

we protected the dynamic library lock inside libc so that we wouldn’t interrupt dlopen while it held the lock. well, here, we interrupted dlsym with a sample while it holds the lock. that conflicts with libunwind, which calls dl_iterate_phdr. back in 2009, we didn't use libunwind. aargh!

**Comment by mwkrentel** [comment]
Yes, indeed.  It's not as frequent and I have to double the sampling
frequency, but I can make it deadlock with only one thread.  The stack
traces are the same with _ULx86_64_dwarf_find_proc_info() and
dl_iterate_phdr() on the stack.

I tried building without libunwind, but the build fails.

```
In file included from ../../../../src/tool/hpcrun/unwind/x86-family/unw-datatypes-specific.h:50:0,
                 from ../../../../src/tool/hpcrun/unwind/common/unw-datatypes.h:51,
                 from ../../../../src/tool/hpcrun/unwind/common/backtrace.h:73,
                 from ../../../../src/tool/hpcrun/cct/cct.h:84,
                 from ../../../../src/tool/hpcrun/cct/cct_bundle.h:51,
                 from ../../../../src/tool/hpcrun/cct_insert_backtrace.c:51:
../../../../src/tool/hpcrun/unwind/common/std_unw_cursor.h:56:10: 
fatal error: libunwind.h: No such file or directory
```

It's kinda odd that unwind/common relies on libunwind.  This used to
be allowed to build without libunwind.  So, that's a regression.

----------

For a single-thread deadlock (locking against yourself in a
sighandler), I think we already keep track of whether we're inside
dlopen().  So we disallow calling libunwind in this context and drop
the sample if needed.

For a multiple-thread LOR, the necessary order in hpcrun (going back
to e25daa550ccc from 2009) is:

```
  dl_iterate_phdr  (system lock)
  fnbounds lock
  ui-tree lock
```

So, if we already hold the fnbounds or ui-tree lock, then we can't
call libunwind.  Again, drop the sample.

**Comment by jmellorcrummey** [comment]
> So, if we already hold the fnbounds or ui-tree lock, then we can't
> call libunwind. Again, drop the sample.

Or, we could try the native unwinder.

**Comment by mxz297** [comment]
#216 is a fix that suppress samples during dlopen and dlclose. It does not address dlsym. 

In addition, there is similar code in the code base including

https://github.com/HPCToolkit/hpctoolkit/blob/a6f7962ad1041fe1834cb7fdfcea45258690e5f0/src/tool/hpcrun/thread_data.h#L280

and 

https://github.com/HPCToolkit/hpctoolkit/blob/master/src/tool/hpcrun/hpcrun_flag_stacks.c#L7

We will need to clean and unify these pieces.

**Comment by mxz297** [comment]
@jmellorcrummey @mwkrentel @blue42u 

I have a possible solution to solve this problem. With #216, our current obstacle is dlsym. Previously, we focus on wrapping dlsym, which is tricky to do even with GOACHA. In addition, Spectrum MPI may wrap dlsym in a way that might make it impossible for us to safely wrap dlsym and be compatible with Spectrum MPI. 

So, Jonathon and I have been thinking about a solution that get rid of the call to `dl_iterate_phdr` in libunwind. The basic idea is to intercept the `dl_iterate_phdr` call in libunwind and replace it with our implementation of `dl_iterate_phdr` (let's call it `hpcrun_dl_iterate_phdr`). Note that we call `dl_iterate_phdr` durning the handling of dlopen, so we can make copies of `struct dl_phdr_info` objects and provide them to the callback in libunwind. To libunwind, it looks as if it is calling the real `dl_iterate_phdr`. 

The first question is then how can we intercept `dl_iterate_phdr` call in and only in libunwind. I find that GOTCHA has an internal interface that allows GOT rewriting for a specific library. So I used that internal interface to only rewrite GOT inside libunwind.so. In this way, libhpcrun.so will still call to the real `dl_iterate_phdr`, but libunwind's calls to `dl_iterate_phdr` are replaced with calls to `hpcrun_dl_iterate_phdr`. If the whole thing works out, we will want to create PR to GOTCHA to expose this interface.

The second piece is to replace the lookup for CUDA function using dlopen/dlsym with elf symbol table lookup. This is necessary because otherwise a thread will still deadlock itself. Currently, I just disable the code entirely to see if it can possibly work. Libunwind actually provides code examples to show how to get an ELF section from a `struct dl_phdr_info`, so this is definitely doable.

The third piece is to clean up all the reader/writer lock code. At this point, I think we only need a mutex lock for protecting our own load map during loading and unloading a library; the `fnbounds_lock` in fnbounds_dynamic.c serves this purpose well. So, I believe we can just get rid of the whole reader/writer lock.

To this point, I can ran Mark's full stress test (including dlopen/dlsym/dlclose) without any hang (in 100 rans). It definitely does not mean my code is ready for merge, but I think it shows that this a promising solution and we do not necessarily need to wrap dlsym.

**Comment by jmellorcrummey** [comment]
this seems like a very promising approach for handling libunwind. we may need to consider the static linking case too though. static linking seems to be falling out of fashion these days. we need to understand plans for Cray platforms.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/200)
