### ISSUE TITLE
ompt-blame branch doesn't combine metrics across threads correctly

### ISSUE THREAD

**Issue by mwkrentel** [HPCToolkit/hpctoolkit#268]
There's another problem with the openmp support.  For the ANL demo on
theta, I ran amg2006 + llvm-openmp libomp + your ompt branch.
Something is doing cut-and-paste for the call paths (correct), but not
correctly adding the metrics.

amg2006 + ompt branch + llvm libomp.a + OMP_IDLE:

For openmp loop # 8, the bottom-up and flat reviews report this as
17.6% for REALTIME.  But top-down reports only 1.3%.  That value would
be correct for a single thread, but not with master + side threads
combined with ompt support.

The problem is not multiple paths to omp # 8.  Expanding bottom-up
shows only one path.

amg2006 + 2020.03.01 release doesn't combine the two paths, but there,
bottom-up reports two paths, 1.2% from main (master thread) and 16.8%
from thread root.

Although oddly, top-down reports 0.1%, not 1.2%, again off by a factor
of 10-15 (this was 16 threads).  So maybe there's a more fundamental
problem.

I put two tar files on nancy.  Each one has the measurements and
database directories.

-rw-r--r--   1 krentel hpc 2887626 May  6 22:25 amg-hpc-master.tar.gz
-rw-r--r--   1 krentel hpc 3749792 May  6 22:25 amg-ompt.tar.gz

If amg2006 is too many threads (8 ranks x 16 threads), I could
probably write a smaller test where this happens.  Unless of course,
the bug depends on something complicated in the amg runtime.

@jmellorcrummey 

![bottom-up](https://user-images.githubusercontent.com/3969036/81253214-9cdd6e80-8fed-11ea-858e-8f6268bc96f1.png)

![top-down](https://user-images.githubusercontent.com/3969036/81253228-a9fa5d80-8fed-11ea-8eda-1f5f1eaca57c.png)

**Comment by laksono** [comment]
The bottom-up view depends on the flat (or static) ID to combine the call path. 
In your case, the bottom-up view of procedure `hypre_CSRMatrixMatvecT._omp_fn.8` is a combination of 4 different call-paths since they all have the same static ID. The snapshot below shows 2 different call-paths of `hypre_CSRMatrixMatvecT._omp_fn.8`:

![image](https://user-images.githubusercontent.com/8781032/81287232-0b3f2280-9028-11ea-8095-b61662cd2fb6.png)

**Comment by jmellorcrummey** [comment]
This problem is related to problems that have come up several times recently (e.g., with quicksilver, and with some stripped example that I produced recently with lots of unknown procedures). It is time for a discussion about a re-design of the support for constructing bottom-up and flat views.

@laksono : please draft a document to get the process started. The document should include:
- a list of requirements for correct construction of views by hpcviewer for bottom-up and flat cases? 
- a list of known conditions that currently cause problems
- a discussion of recent changes to address recent problems with this capability (i.e. for quicksilver, unknown procedures) and why the changes to address these cases were not enough.

**Comment by laksono** [comment]
It's a different problem with quicksilver. This time it's a pure hpcviewer problem.

As we know hpcviewer constructs the bottom-up tree based on static IDs. 
During the bottom-up tree construction, when it encounters a call site, it just takes into consideration the static ID of the procedure frame (PF). It doesn't consider the static ID of the line statement of the call.

The snapshot below shows that the call site in purple boxes have the same procedure static ID, but have **different call site static ID**:

![image](https://user-images.githubusercontent.com/8781032/81302075-7fd18b80-903f-11ea-845e-f1cff1ca8e20.png)

The following bottom-up tree construction code shows that: if two nodes have the same procedure scope static ID, we'll merge them. Interestingly, it doesn't take into account the call sites.

```
			//------------------------------------------------------------------------
			// we check if the scope is identical with the existing scope in the path
			// if it is the case, we should merge them
			//------------------------------------------------------------------------
			final ProcedureScope firstProc  = first.getProcedureScope();
			final ProcedureScope callerProc = existingCaller.getProcedureScope();
			
			String firstID  = String.valueOf(firstProc.getFlatIndex());
			String callerID = String.valueOf(callerProc.getFlatIndex());
						
			if (firstID.equals(callerID)) {

				//------------------------------------------------------------------------
				// combine metric values for first to those of existingCaller.
				//------------------------------------------------------------------------
				combine.combine(existingCaller, first, inclusiveOnly, exclusiveOnly);
```
Keep in mind, this is **an old algorithm**. A long time ago perhaps we shouldn't consider the call site (perhaps because of double aliens at that time?). I think we should consider the call site too, but I don't remember why we decided against it.

**Comment by laksono** [comment]
There are many cases where the merge based on procedure static ID only is desirable.
As shown below, procedure `GOMP_parallel` (static ID: 25743) are called by different instances of `inline from hypre_smp_forloop.h` (the snapshot below is the original hpcviewer):

![image](https://user-images.githubusercontent.com/8781032/81315900-87e5f700-9050-11ea-84f6-ea56c0d2c5cd.png)

If we don't want to merge the call sites (different instances of `inline from hypre_smp_forloop.h`) then the tree looks more confusing due to so many branches. The snapshot below is the **MODIFIED** hpcviewer where we don't merge if the two call sites are different:

![image](https://user-images.githubusercontent.com/8781032/81316078-bebc0d00-9050-11ea-8af1-e3e3e6a25e43.png)

Here, we have several `GOMP_parallel` nodes because they're called by different instances of `inline from hypre_smp_forloop.h`.

I can see why we decided to merge based on the procedure frame only, and I think it's a good choice. However, to avoid confusion, we should *annotate* a merged node. Even better if we can show the relationship between a node in the bottom-up tree to nodes in the top-down tree (one-to-many relationship).

**Notes**: the first number (177847) is the static ID of the call site. The second number (25743) is the static ID of the procedure frame:

![image](https://user-images.githubusercontent.com/8781032/81316955-d942b600-9051-11ea-9d49-45f1d9af0379.png)

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/268)
