### ISSUE TITLE
deadlock when profiling an application that uses libtcmalloc

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#28]
For a configuration of tcmalloc on follis, hpcrun deadlocks when tcmalloc calls dlopen. The situation is this: to provide performance monitoring, tcmalloc uses unwinding. In the course of initializing unwinding, dlopen is called.  hpcrun wraps dlopen and calls dlsym to locate it, dlerror calls malloc, malloc spins on a lock that the thread already holds.

Using tcmalloc_minimal worked. We need two things:
(1) short term: document the problem and the solution in our trouble shooting guide
(2) see if we can use gotcha rather than preloading to wrap dlopen

**Comment by mwkrentel** [comment]
I started looking at this as an example of difficult code paths for
libmonitor.

First, the mechanics of the deadlock with the full tcmalloc are:

1. tcmalloc gains control in an init constructor (either its own init
ctor or a malloc override, I'm not sure), tcmalloc acquires a lock and
then calls libunwind.

2. libunwind calls sigprocmask.

3. monitor overrides sigprocmask and calls dlsym and dlerror which
call malloc, and deadlock.

This is why tcmalloc_minimal works, it eliminates libunwind in step 2.

Note: dlsym calls malloc itself, so it doesn't help to remove the
dlerror step.

IMO, tcmalloc is living dangerously by calling 3rd party libunwind.
tcmalloc implements malloc, so it better be 100% certain that
libunwind never has a stray printf or strdup or some such, or else it
will deadlock all on its own.

Anyway, tcmalloc_minimal implements all of the malloc functions, so
it's a perfectly satisfactory workaround.  (Again, IMO, minimal should
be the norm and the full tcmalloc should be considered "enhanced with
extra debugging, but potentially dangerous.")

----------

As for gotcha, this is not a perfect solution.  Gotch is fundamentally
blind to init constructors.  So, if a library creates a thread from an
init ctor, then gotcha doesn't catch it.

https://github.com/LLNL/GOTCHA/issues/83

Although gotcha avoids the deadlock from preload, it does so not by
being safer, but because you don't get the override.

So, if we use gotcha to wrap function calls, then we miss the calls
from an init constructor.  (Maybe that's safer by itself.)  But maybe
a hybrid solution of preload for pthread_create and __libc_start_main,
etc, and gotcha for the rest might make sense.

**Comment by jmellorcrummey** [comment]
is this dlsym and dlopen issue fixed by the auditor?

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/28)
