### ISSUE TITLE
More types for metrics are needed

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpctoolkit#305]
@jmellorcrummey: I move hpcviewer issue #97 (https://github.com/HPCToolkit/hpcviewer/issues/97) to here since this is related to hpcrun and hpcprof.

There is a type **HPCRUN_FMT_METRIC_SHOW_EXCLUSIVE**, which is used for the details of exclusive metrics describing a kernel. 
There should also be a type of **HPCRUN_FMT_METRIC_HIDE_EXCLUSIVE** that can potentially show only the exclusive, but it will start hidden.

Current metric visibility type (defined in [hpcrun-fmt.h](https://github.com/HPCToolkit/hpctoolkit/blob/4cfbc0dd0fb55677c460e007bade6d0d403b230f/src/lib/prof-lean/hpcrun-fmt.h#L165-169)):
```
#define HPCRUN_FMT_METRIC_HIDE            0
#define HPCRUN_FMT_METRIC_SHOW            1
#define HPCRUN_FMT_METRIC_SHOW_INCLUSIVE  2
#define HPCRUN_FMT_METRIC_SHOW_EXCLUSIVE  3
#define HPCRUN_FMT_METRIC_INVISIBLE       4
```
Suggestions:
- Rename `HPCRUN_FMT_METRIC_SHOW_INCLUSIVE` to `HPCRUN_FMT_METRIC_INCLUSIVE_ONLY`
- Rename `HPCRUN_FMT_METRIC_SHOW_EXCLUSIVE` to `HPCRUN_FMT_METRIC_EXCLUSIVE_ONLY`
- Add `HPCRUN_FMT_METRIC_HIDE_INCLUSIVE` : by default the **inclusive** metric is hidden, but can be shown by hpcviewer later.
- Add `HPCRUN_FMT_METRIC_HIDE_EXCLUSIVE` : by default the **exclusive** metric is hidden, but can be shown by hpcviewer later. 
- Add `HPCRUN_FMT_METRIC_PROCEDURE_ONLY` (metrics such as GPU kernel info which should not be propagated to their enclosing procedure, they should be MOVED there)

**Comment by laksono** [comment]
- For HPCRUN_FMT_METRIC_HIDE_INCLUSIVE, hpcprof will set the visibility attribute of the inclusive metric to "0" (hidden), and keep the visibility attribute of exclusive metric to "1" (shown).
- For HPCRUN_FMT_METRIC_SHOW_EXCLUSIVE, hpcprof will set the visibility attribute of the exclusive metric to "0" (hidden), and keep the visibility attribute of inclusive metric to "1" (shown).

hpcviewer will hide the metrics automatically, and will still allow users to display them.

**Comment by jmellorcrummey** [comment]
I think that what we want to specify is what to compute

HPCRUN_FMT_METRIC_COMPUTE_EXCLUSIVE_ONLY
HPCRUN_FMT_METRIC_COMPUTE_INCLUSIVE_ONLY
HPCRUN_FMT_METRIC_COMPUTE_INCLUSIVE_AND_EXCLUSIVE

where we want to put it

HPCRUN_FMT_METRIC_LOCATION_DEFAULT
HPCRUN_FMT_METRIC_LOCATION_ENCLOSING_PROCEDURE

and how we want it displayed by default:

HPCRUN_FMT_METRIC_INVISIBLE
HPCRUN_FMT_METRIC_HIDE
HPCRUN_FMT_METRIC_SHOW

We should have some set of flag bits for each (perhaps 4 bits for each so that there is room to add more). I would hate to do each category with 1-2 bits and then need to change it later.

**Comment by jmellorcrummey** [comment]
Perhaps we should also explicitly specify who should compute it:

HPCRUN_FMT_METRIC_PROF_COMPUTES
HPCRUN_FMT_METRIC_VIEWER_COMPUTES

**Comment by laksono** [comment]
If I understand, the Metric attribute will be:

```
bits	description
0  	show (1: shown,  0: hidden)
1	visible to the user (1: visible, 0: invisible)
2	-
3	-
4	exclusive (1: create the exclusive metric, 0: do not create)
5	inclusive (1: create the inclusive metric, 0: do not create)
6	-
7	-
8	location procedure (1: procedure level, 0: default)
9	-
10	-
11	-
12	compute in prof (1: formula computed in prof)
13	compute in viewer (1: formula computed in viewer)
14	-
15	-
```

**Comment by jmellorcrummey** [comment]
This looks like a good full design.

If we have a server (like the trace server) helping hpcviewer, it might make sense to compute it in the GUI server rather than in java. that is a potential future enhancement of this design. 

it seems to make sense to have the two bits that determine where it is computed as a value 0, 1, or 2 that indicates which of these three places it is computed rather than as a bit field, which makes it look like it makes sense to compute it in multiple places.

I don't think it makes sense to compute it in both places, so I think it is fine to collapse this to a bit.

Now that I see a full design, it makes sense to collapse this down to 6 contiguous bits.

**Comment by laksono** [comment]
In this case:
```
bits	description            	value
0  	show 			1: shown,  0: hidden
1	visible to the user 	1: visible, 0: invisible
2	exclusive          	1: create the exclusive metric, 0: do not create
3	inclusive 		1: create the inclusive metric, 0: do not create
4	formula computation 	1: formula computed in prof, 0: computed in viewer
5	value propagation 	1: procedure level, 0: default
```

A long time ago we discussed to make the trace server to be more generic: not only it handles trace data, but also profile data. But as usual, we just don't have time to do it.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/305)
