### ISSUE TITLE
Combining inlined functions in the caller's view

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#31]
In the caller's view, looking up from __lll_lock_wait (the second most costly function), the caller _L_lock_791 has more than 20 parents, all instances of an inlined function boost::posix::pthread_mutex_lock (mutex.hpp:62). Why are these parents not all collapsed, as if they would be if they were a real function?

Try hpcviewer on les:/home/johnmc/bugs/viewer-callers-view-bug.tgz to reproduce the problem.

**Comment by laksono** [comment]
@jmellorcrummey : yes this is a bug, but it seems the problem is either from hpcstruct or hpcprof.
The name of the caller is the same, but it has many entries in experiment.xml's procedure table. hpcviewer assumes each procedure ID is unique (although they have the same name), hence it doesn't collapse the function.

$ grep -H -n "boost::posix::pthread_mutex_lock(pthread_mutex_t" experiment.xml
experiment.xml:665:    <Procedure i="13404" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:853:    <Procedure i="25410" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:1683:    <Procedure i="64943" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:1744:    <Procedure i="63205" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:1806:    <Procedure i="64643" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:1869:    <Procedure i="67876" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:2092:    <Procedure i="265993" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:2152:    <Procedure i="266451" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:2175:    <Procedure i="266565" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:2196:    <Procedure i="266675" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:2218:    <Procedure i="266893" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:2234:    <Procedure i="267003" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:2250:    <Procedure i="267121" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:2271:    <Procedure i="268603" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:2287:    <Procedure i="268738" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:2303:    <Procedure i="268839" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:2322:    <Procedure i="268973" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:2348:    <Procedure i="269087" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:2396:    <Procedure i="269244" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:2433:    <Procedure i="270254" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:3112:    <Procedure i="424339" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:4009:    <Procedure i="529458" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:5763:    <Procedure i="614577" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:5809:    <Procedure i="614894" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:5815:    <Procedure i="616968" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:7640:    <Procedure i="708845" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:7660:    <Procedure i="709104" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:7769:    <Procedure i="716139" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:7790:    <Procedure i="717501" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:8292:    <Procedure i="757833" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:9256:    <Procedure i="835450" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:9271:    <Procedure i="835281" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>
experiment.xml:10740:    <Procedure i="871688" n="boost::posix::pthread_mutex_lock(pthread_mutex_t*)"/>

**Comment by jmellorcrummey** [comment]
@mwkrentel Laksono's diagnosis pinpoints the problem being with hpcstruct. We need to make sure that names for inlined functions are obtained from a string table to ensure that identical names are collapsed.

**Comment by jmellorcrummey** [comment]
With the rewrite of hpcstruct, has this issue been addressed or forgotten?

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/31)
