### ISSUE TITLE
2_unwinders needs to be reverted out of master until performance improves

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#37]
@unkadoug @mwkrentel The 2_unwinders code introduces a significant performance bottleneck that dilates the execution time of a 48-core code run with -e REALTIME@1000 by 10x. It appears that the fnbounds interface, which employs mutual exclusion, is interrogated at every sample to determine the address range of a function.

**Comment by unkadoug** [comment]
This message does not make clear who is to remove the 2_unwinders changes from master.

2_unwinders does nothing in particular with respect to when fnbounds is invoked, and the same behavior will remain in master, and need to be fixed in master, even if the 2_unwinders changes are removed.  That behavior will only be evident when -enable-libunwind-primary is used.  Perhaps this problem has always been present with -enable-libunwind-primary, but is only now recognized as a problem.

**Comment by jmellorcrummey** [comment]
I thought we would discuss the issue in the meeting at 4pm today, decide how to adjust the git repository, and decide who would do it. I didn't assign anyone until we discussed what exactly should be done.

**Comment by jmellorcrummey** [comment]
performance issue addressed
