### ISSUE TITLE
hpcrun -L creates measurement directory

### ISSUE THREAD

**Issue by mwkrentel** [HPCToolkit/hpctoolkit#377]
Something has changed in the startup sequence of hpcrun in develop
causing the measurements directory to be created too early.  For
example, running 'hpcrun -L' creates a measurement directory (it
shouldn't).

Similarly, 'hpcrun -e NONE' also creates a measurements directory
(again, it shouldn't).

```
$ ls -l
total 68K
-rwxr-xr-x. 1 krentel users 21643 Jan 27 22:16 hpclink
-rwxr-xr-x. 1 krentel users  6059 Jan 27 22:15 hpcprof
-rwxr-xr-x. 1 krentel users 26846 Jan 27 22:16 hpcrun
-rwxr-xr-x. 1 krentel users  6065 Jan 27 22:15 hpcstruct

$ ./hpcrun -L
... (lots of output) ...

$ ls -l
total 72K
-rwxr-xr-x. 1 krentel users 21643 Jan 27 22:16 hpclink
-rwxr-xr-x. 1 krentel users  6059 Jan 27 22:15 hpcprof
-rwxr-xr-x. 1 krentel users 26846 Jan 27 22:16 hpcrun
-rwxr-xr-x. 1 krentel users  6065 Jan 27 22:15 hpcstruct
drwxr-xr-x. 3 krentel users  4096 Jan 27 22:21 hpctoolkit-ls-measurements
```

Worse yet, if you happen to be in a directory without write
permission, you get:

```
$ ./hpcrun -L
hpcrun: could not create output directory `./hpctoolkit-ls-measurements': Permission denied
(but no output)
```

This doesn't happen in 2020.08.03 or in master.

**Comment by mxz297** [comment]
@jmellorcrummey @mwkrentel I compared the startup sequence of hpcrun between the master branch and the develop branch. The develop branch has significantly reordered the hpcrun startup sequence for the gpu tracing support. My belief is that this bug is not trivial to fix as it involves changing our fragile startup code, and I would argue that we should defer this bug after the release and rework our startup code in a principled way, considering we also have the startup issue regarding PAPI and HSA.

In the develop branch, there is a comment block stating:

```
// We initialize the load map and fnbounds before registering sample source.
// This is because sample source init (such as PAPI)  may dlopen other libraries,
// which will trigger our library monitoring code and fnbound queries
```
If I use "A < B" to represent that operation A happens before operation B, based on the above comments, "fnbounds init" < "registering sample source".

Then:

```
  // We need to initialize messages related functions and set up measurement directory,
  // so that we can write vdso and prevent fnbounds print messages to the terminal.
```

For this reason, "creating measurement directory" < "fnbounds init" < "registering sample source".

Finally, as `hpcrun -L` requires sample sources to be registered first so that each sample source can report whether it can be functional or not. We have:

"creating measurement directory" < "fnbounds init" < "registering sample source" < "listing available events"

To move "creating measurement directory" after "listing available events", we must break one of the dependencies and it is not obvious to me what we can do here without potentially introducing side effects.

**Comment by mwkrentel** [comment]
@jmellorcrummey @mxz297 
I can tell that we have more "software debt" to pay in this area, as
Scott would say.  I agree that we probably should rethink the entire
startup sequence, including all the "irregular" entry points.

Here's a sleazy "temporary" solution, at least let's plan on temporary.

AFAIK, this is only an issue for -L and -e NONE.  (IIRC, -V is handled
in the script and never execs the app.)  In the hpcrun launch script,
when we read the -L or -e options, add an extra environ variable,
maybe HPCRUN_NO_MEASUREMENT_DIR=1 and then test for that before
creating the measurement directory.   Btw, NONE is really more for the
static case, dynamically you could just skip the hpcrun script altogether.

Either that, or we could test for the same thing as a preliminary step
inside hpcrun.  It shouldn't be hard to do an early scan of HPCRUN_EVENT_LIST
for LIST or NONE and treat this case specially.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/377)
