### ISSUE TITLE
hpcprof takes long time and no response

### ISSUE THREAD

**Issue by SubjectNoi** [HPCToolkit/hpctoolkit#404]
After I used `mpirun -np 3 hpcrun .....`, `hpcstruct`, I used `hpcprof-mpi -S ... -I ... [measure dir]`, however, I wait a long time but this command only give me following output:
```
 % hpcprof -S main.hpcstruct -I ../src/wrapper_mpi_new.cpp hpctoolkit-main-measurements
msg: STRUCTURE: ~/workspace/MultiVersion/DefaultImplFinder/cpp_wrapper_multi_process/build/main
msg: Line map : ~/workspace/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/hpctoolkit-2021.03.01-ucxspqiohaofwv5pno64q2exzvgveqq3/lib/hpctoolkit/libhpcrun.so
msg: Line map : ~/workspace/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/hpctoolkit-2021.03.01-ucxspqiohaofwv5pno64q2exzvgveqq3/lib/hpctoolkit/ext-libs/libmonitor.so.0.0.0
```

And there's nothing in main database dir, is there something wrong or I just need to wait for more time?

**Comment by jmellorcrummey** [comment]
The delay you see is because hpcprof is analyzing all of the libraries that your application depends upon. Based on your report that this is running for a long time, I would guess that there is one or more large library that your application depends upon. If you run the command “ldd main” you should see most of the libraries that main will load, except for those loaded by dlopen (if you are using openmpi, there will be many). one way that you can accelerate hpcprof is to use hpcstruct to compute hpcstruct files for each dynamic library loaded by your application. you can pass additional hpcstruct files to hpcprof by using -S more than once. When you analyze a binary with hpcstruct, you can analyze it in parallel by passing the -j option to hpcstuct.

**Comment by Jokeren** [comment]
@SubjectNoi 

Tip: Add  `DIAG_MsgIf(true, "Begin analyzing : " << this->m_name);` at https://github.com/HPCToolkit/hpctoolkit/blob/78f8ead70a2d8ca6303216d69eaa6b9c725b5c39/src/lib/binutils/LM.cpp#L1000

Recompile and install hpctoolkit. Then you can check at which libraries hpcprof is stuck and use `hpcstruct -j` on these libraries.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/404)
