### ISSUE TITLE
can't use events realtime and cputime using lower case

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#459]
using cputime gives an error. it should measure using CPUTIME. lower case is a convenience.
using realtime matches a perf raw event. I thought this was fixed but apparently not. the bug is in master.

**Comment by laksono** [comment]
@jmellorcrummey the realtime event should be fixed. Which branch are you referring to?
The fix was in the develop branch few week ago (I think it should be merged to master now):
https://github.com/HPCToolkit/hpctoolkit/commit/441689bbf4a9972951955f7803703a5e71e4f8e6#diff-82873c574f4503d1f0904d040b742dc7bd42c7e75390a32d5d71d44acb902128

Btw I completely agree that we should allow lower case for the event names, but someone disagree with that :-).

**Comment by laksono** [comment]
@blue42u Thanks for the info. This means the patch will be available for the next release.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/459)
