### ISSUE TITLE
hpcrun on hpcstruct generates spurious monitor error message

### ISSUE THREAD

**Issue by martyitz** [HPCToolkit/hpctoolkit#523]
monitor warning [1404889,0] monitor_execve: unexpected execve failure on pid: 1404889

It is definitely related to a call to system to launch a script to correct the pathname in a structure file
obtained from the cache, but generated on an identical binary at a different pathname.  There is no
evidence that any harm is indicated by the message.

**Comment by mwkrentel** [comment]
We tracked this down to a typo in the rename launch script that
started `#/bin/sh` instead of `#!/bin/sh`.   Monitor sees `exec()` 
for the rename script, the file exists, it has execute permission, 
so monitor expects exec() to succeed.   When it doesn't, monitor 
reports this warning.

This is now fixed in master.
