### ISSUE TITLE
Attribute kernel time to <vmlinux> when kptr_restrict = 1

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#56]
When /proc/kallsyms maps all symbols to 0, we don't just collapse the callstack and attribute it to <vmlinux>. See the attached viewer snapshot which shows what I see on theta. scatterwalk_start is a kernel routine. we didn't record any symbol files.

<img width="441" alt="bad-kernel-attribution" src="https://user-images.githubusercontent.com/3926112/36479003-ad16b6fe-16cc-11e8-888b-7e3c62d64b63.png">

**Comment by laksono** [comment]
This issue is redundant with issue  #44 ([kernel call chains when /proc/sys/kernel/kptr_restrict=1](https://github.com/HPCToolkit/hpctoolkit/issues/44)).
This has been fixed in mult-kernel branch commit dc9decd703daa455f2f51751b54301d9efa355eb (see https://github.com/HPCToolkit/hpctoolkit/commit/dc9decd703daa455f2f51751b54301d9efa355eb).
We need to validate this branch before we merge back to the master.

**Comment by mwkrentel** [comment]
Fixed in mult-kernel, soon to be master, so close.
