### ISSUE TITLE
hpcstruct computes wrong name for inlined functions with single-character names

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#63]
hpcstruct produces the wrong names for most single character inlined functions. Either hpcstruct or dyninst is demangling these names into type names. The test in the directory below illustrates the problem. 

https://github.com/HPCToolkit/hpctoolkit-tests/tree/master/src/tool/hpcstruct/test1

**Comment by jmellorcrummey** [comment]
I looked at this case in the debugger. Dyninst is putting a pretty name into each InlinedFunction object in the name_ field. Thus, in Struct-Inline.cpp, when we call func->getName() we get a pretty name back. I venture a guess that we are calling the demangler on what we get back. So, my assessment is that the problem is in hpcstruct and not that we are getting back an incorrectly detangled name from Dyninst.

**Comment by mwkrentel** [comment]
It's complicated.  Certainly, there are cases where hpcstruct
demangles a name when it shouldn't.  But the inline names from
func->getName() normally are mangled, so with C++ test, they would
look right in the viewer.

The fundamental problem was that for function names that don't come
from an actual function in the symbol table, there is no single right
answer for whether the name should be demangled or not.  Hpcstruct
needs more info to decide if demangling is correct and it wasn't doing
that.

I've done an overhaul on how and when hpcstruct demangles function
names.  There are three major cases:

1. A full symtab function for an actual function in the symbol table.
Symtab provides separate mangled and pretty names, so we just use
their answer.

2. An inline callsite.  Symtab provides only a single (normally
mangled) name.  Lookup the module and source language for the vma to
decide whether to demangle or not.

3. A PLT function stub.  There are no modules or source files for
these stubs.  Demangle the name and heuristically decide if the answer
is right (if the name contains parens).

There are also outline function names.  But we make a fake name for
these functions, so demangling is not an issue.

This is now fixed in mult-kernel, commit a9559d33c2 on 2018-03-28.
So, the issue should be closed.

**Comment by mwkrentel** [comment]
mult-kernel is now merged into master,
so ok to close.
